### ISSUE TITLE
Вопрос: от какой версии/ревизии xUnitFor1C произошли доработки в проекте?

### ISSUE THREAD

**Issue by artbear** [ripreal/1C_HomeAssistant#1]
Огромный плюс за использование xUnitFor1C, да еще в мобильной разработке.

Вопрос - какая версия xUnitFor1C являлась базовой для доработок в проекте?

**Comment by artbear** [comment]
И еще один вопрос - какие изменения были сделаны в xUnitFor1C ?

**Comment by ripreal** [comment]
Использовал 4.0.0.7.
Изменения в обработках ЗагрузчикИзПодсистемКонфигурации, ЗагрузчикФайла.  Главным образом убраны обращения к отсутствующим в мобильной платформе объектам: Отчеты, ВнешниеОтчеты, ТекстовыйДокумент и др.

При этом я использовал только минимум модулей для загрузки тестов из конфигурации (странно, что приходится обязательно использовать ЗагрузчикФайла)

**Comment by artbear** [comment]
А как дела с асинхронностью? для мобильной платформы нужна асинхронность?

**Comment by ripreal** [comment]
У меня не было с этим проблем. На самом мобильнике xUnitFor1C не запускается, он запускется только на ПК.
